apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ayush729874/jenkins-build.git
    targetRevision: HEAD
    path: test_builds
  destination:
    server: https://kubernetes.default.svc
    namespace: test

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
